// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 26/02/2025, 15:12:36
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/Prontifica/markdown-to-pdf/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Prontifica/markdown-to-pdf/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Prontifica/markdown-to-pdf/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Prontifica/markdown-to-pdf/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Prontifica/markdown-to-pdf/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Prontifica/markdown-to-pdf/frontend/plugins/**/*.{js,ts,mjs}","C:/Users/Prontifica/markdown-to-pdf/frontend/assets/**/*.{js,ts,mjs}","C:/Users/Prontifica/markdown-to-pdf/frontend/public/**/*.{js,ts,mjs}","C:/Users/Prontifica/markdown-to-pdf/frontend/stores/**/*.{js,ts,mjs}","C:/Users/Prontifica/markdown-to-pdf/frontend/components/**/*.{js,ts,mjs}","C:/Users/Prontifica/markdown-to-pdf/frontend/composables/**/*.{js,ts,mjs}","C:/Users/Prontifica/markdown-to-pdf/frontend/composables/*/index.{ts,js,mjs,mts}/**/*.{js,ts,mjs}","C:/Users/Prontifica/markdown-to-pdf/frontend/composables/**/**/*.{js,ts,mjs}","C:/Users/Prontifica/markdown-to-pdf/frontend/util/*.{ts,js,mjs,mts}/**/*.{js,ts,mjs}","C:/Users/Prontifica/markdown-to-pdf/frontend/utils/**/*.{js,ts,mjs}","C:/Users/Prontifica/markdown-to-pdf/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Prontifica/markdown-to-pdf/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Prontifica/markdown-to-pdf/frontend/app.config.{js,ts,mjs}","C:/Users/Prontifica/markdown-to-pdf/frontend/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;